CREATE VIEW [AppUser].[V_Book_Full]
	AS SELECT 
	 [Object].[Id]
	,[Object].[Price]
	,[Object].[Curr]
	,[Object].[ShopId]
	,[Object].[Date]
    ,[Object].[Signed]
	,[Object].[SignedBy]
	,[Object].[EAN]
	,[Object].[EAN_EXT]
	,[Object].[Comment1]
	,[Object].[Comment2]
	,[Object].[Onwed]
	
	,[Books].[Serie]     
	,[Books].[Title]     
	,[Books].[Writer1]   
	,[Books].[Writer2]   
	,[Books].[Language]  
	,[Books].[Edition]   
	,[Books].[Format]    
	,[Books].[Number]    
	,[Books].[Pages]     
	,[Books].[YEAR]      
	,[Books].[FirstPrint]

	FROM [Object] 
	INNER JOIN [Books] on [Object].[Id] = [Books].[Id] 
	WHERE [Object].[TypeId] = 2